name: lands
version: 0.0.0

ghc-options: >-
  -Wall
  -Wincomplete-uni-patterns
  -Wincomplete-record-updates

default-extensions:
  - ApplicativeDo
  - GADTs
  - KindSignatures

dependencies:
  - base == 4.9.1.0
  - bytestring == 0.10.8.1
  - MonadRandom == 0.5.1

library:
  source-dirs:
    - src

executables:
  lands:
    source-dirs:
      - app
    main: Main.hs
    dependencies:
      - lands
